#Multiple linear regression using Sklearn to predict the gpa based on SAT score and a random value of 1 to 3
###The outcome is a feature selection to find which variable is not adding value to the model

##Import libraries and load data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set() #set to the default style

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('/content/1.02.+Multiple+linear+regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

##Creating the miltiple linear regression

###Declaring the dependent and independt variables

In [4]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

###Regression

In [6]:
reg = LinearRegression()
#we dont need to transform the x value into a matrix as we do in linear regression
reg.fit(x,y)

LinearRegression()

In [7]:
reg.coef_
#the first value is for the SAT, second for Rand 1,2,3

array([ 0.00165354, -0.00826982])

In [8]:
reg.intercept_

0.29603261264909486

##R-Squared

In [9]:
reg.score(x,y )

0.4066811952814283

##Adjusted R-Squared
###To get more accurate measurements

In [10]:
x.shape

(84, 2)

In [12]:
r2 = reg.score(x,y)
n = x.shape[0] #number of observations
p = x.shape[1] #number of features

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

####As the adjusted R-squared is less than the R-squared, it shows that theres a variable that is not adding value to the model.
####To find out which variable, we use the p value
####p-value > 0.05, we can disregard it  

##Feature selection
####F-regression creates simple linear reg of each feature and the dependant variable.
####For a simple linear regression, the p value of F-Stat is equivilent to the p value of the only independent variable

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y)
#First array is the F-statistics, the second array is the p values

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [15]:
#As we are only interested in the p value, we need to extract it
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [16]:
p_values.round(3)
#The first value is SAT, second is Rand 1,2,3

array([0.   , 0.676])

####As Rand 1,2,3 had a p-value>0.05 it shows that it is useless and not adding value to the model.
####While the p-value of SAT is 0, it shows that it is highly significant in predicting the SAT score

###the f-regression does NOT take into account the interrelation of the features

##Creating a summary table

In [17]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [19]:
#Adding 2 columns
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676