#Multiple linear regression using Sklearn to predict the gpa based on SAT score and a random value of 1 to 3
###The outcome is a feature selection through Standardization to find which variable is not adding value to the model

##Import libraries and load data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set() #set to the default style

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('/content/1.02.+Multiple+linear+regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

##Creating the Multiple Regression

In [7]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

##Standardzation

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(x) #Calculates the mean and standard deviation of each feature

StandardScaler()

In [12]:
x_scaled = scaler.transform(x) #The actual scaling

In [17]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

##Regression with scaled features

In [18]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [20]:
print(reg.coef_)
print(reg.intercept_)

[ 0.17181389 -0.00703007]
3.330238095238095


##Summary Table

In [21]:
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [22]:
reg_summary #the closer the weight to 0, the lesser the impact

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

##Making predictions

In [23]:
#New data to predict the GPA
new_data = pd.DataFrame(data=[[1700, 2], [1800, 1]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [24]:
reg.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

###As the predicted output makes no sense, we know that new data must be standarized in the same way as the train data

In [25]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [26]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

#Removing the Rand 1,2,3 column

In [27]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1) #only extracting the first column
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [31]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

##The results are almost exactly identical. This shows that the column Rand 1,2,3 has minimal to no effect on the model